# Generated by Django 3.0.6 on 2020-06-02 19:53

import django.core.validators
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, null=True)),
                ('national_id', models.IntegerField(null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('age', models.IntegerField(null=True)),
                ('jail_name', models.CharField(max_length=70, null=True)),
                ('governerate', models.CharField(max_length=70, null=True)),
                ('convection_date', models.DateField(blank=True, null=True)),
                ('jail_time', models.IntegerField(null=True)),
                ('no_of_dependents', models.IntegerField(null=True)),
                ('total_target', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('details', tinymce.models.HTMLField(null=True)),
                ('is_approved', models.BooleanField(blank=True, null=True)),
                ('is_featured', models.BooleanField(blank=True, null=True)),
                ('featuring_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
