# Generated by Django 3.0.6 on 2020-06-11 20:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_auto_20200607_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='national_id',
            field=models.CharField(max_length=14, null=True, validators=[django.core.validators.RegexValidator('^(2|3)[0-9][1-9][0-1][1-9][0-3][1-9](01|02|03|04|11|12|13|14|15|16|17|18|19|21|22|23|24|25|26|27|28|29|31|32|33|34|35|88)\\d\\d\\d\\d\\d$', message='please enter a valid egyptian national ID')]),
        ),
    ]
