# Generated by Django 3.0.6 on 2020-06-11 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_auto_20200611_2039'),
        ('cases', '0004_auto_20200611_2009'),
    ]

    operations = [
    ]
