# Generated by Django 3.0.6 on 2020-06-13 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_merge_20200611_2134'),
        ('cases', '0005_merge_20200612_1842'),
    ]

    operations = [
    ]
