# Generated by Django 3.0.6 on 2020-06-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_auto_20200613_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='convection_date',
            field=models.DateField(null=True),
        ),
    ]
