# Generated by Django 3.0.6 on 2020-06-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_auto_20200614_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6),
        ),
    ]
