# Generated by Django 3.0.6 on 2020-06-27 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_auto_20200627_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='is_approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='is_featured',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
