# Generated by Django 3.0.6 on 2020-06-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_auto_20200624_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
