# Generated by Django 3.0.6 on 2020-06-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_auto_20200624_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
